### ISSUE TITLE
[ERR] failed to upload the public key on the machine

### ISSUE THREAD

**Issue by lmilbaum** [tsebastiani/openspot-ng#1]
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] waiting sshd to become ready on 34.213.33.191, hang on....
[INF] swapping default key with the one just created
Warning: Permanently added '34.213.33.191' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for 'id_ecdsa_crc' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "id_ecdsa_crc": bad permissions
core@34.213.33.191: Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
lost connection
[ERR] failed to upload the public key on the machine @ 34.213.33.191

**Comment by lmilbaum** [comment]
I have reason to believe that the root cause is with the default key.  Would it make to generate an EC2 Key Pair as part of the bootstrapping process instead of swapping the default key?

**Comment by lmilbaum** [comment]
I have reason to believe that the keypair private file used to upload the new keypair public file doesn't exist. 
The keypair generated by line #49 prints the private key value to stdout.  I didn't find where it is grabbed and saved in a file. Could that be the root cause?

**Comment by tsebastiani** [comment]
It was simple as ssh was suggesting, the private key must have stricter permissions, unfortunately git doesn't keep file permissions, added a chmod to the script. Thank you very much for the catch and for opening the first issue though!!! 🎉🎉🎉🎉🎉
